/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientProgress {
  'thighInch' : number,
  'chestInch' : number,
  'neckInch' : number,
  'hipsInch' : number,
  'weightKg' : number,
  'timestamp' : Time,
  'waistInch' : number,
}
export type ClientStatus = { 'active' : null } |
  { 'paused' : null };
export interface ClientSummary {
  'status' : ClientStatus,
  'endDate' : [] | [Time],
  'activatedAt' : [] | [Time],
  'code' : bigint,
  'name' : string,
  'pauseTime' : [] | [Time],
  'mobileNumber' : string,
  'planDurationDays' : bigint,
  'followUpDay' : [] | [FollowUpDay],
  'onboardingState' : OnboardingState,
  'startDate' : [] | [Time],
}
export interface ExtendedClient {
  'status' : ClientStatus,
  'pauseEntries' : Array<PauseEntry>,
  'endDate' : [] | [Time],
  'activatedAt' : [] | [Time],
  'code' : bigint,
  'name' : string,
  'pauseTime' : [] | [Time],
  'totalPausedDuration' : bigint,
  'mobileNumber' : string,
  'followUpHistory' : Array<FollowUpEntry>,
  'planDurationDays' : bigint,
  'progress' : Array<ClientProgress>,
  'notes' : string,
  'followUpDay' : [] | [FollowUpDay],
  'onboardingState' : OnboardingState,
  'startDate' : [] | [Time],
}
export type FollowUpDay = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface FollowUpEntry {
  'done' : boolean,
  'notes' : string,
  'timestamp' : Time,
  'followUpDay' : FollowUpDay,
}
export type OnboardingState = { 'full' : null } |
  { 'half' : null };
export interface PauseEntry {
  'durationDays' : bigint,
  'resumed' : boolean,
  'timestamp' : Time,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateClient' : ActorMethod<[bigint, Time, FollowUpDay], undefined>,
  'addProgress' : ActorMethod<
    [bigint, number, number, number, number, number, number],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<
    [string, string, bigint, string, OnboardingState],
    bigint
  >,
  'filterClientsByOnboardingState' : ActorMethod<
    [OnboardingState],
    Array<ExtendedClient>
  >,
  'getActivatedClientSummaries' : ActorMethod<[], Array<ClientSummary>>,
  'getAllClients' : ActorMethod<[], Array<ExtendedClient>>,
  'getAllClientsAndNonActivatedClients' : ActorMethod<
    [],
    {
      'fullOnboardedClients' : Array<ExtendedClient>,
      'halfOnboardedClients' : Array<ExtendedClient>,
      'activatedClients' : Array<ExtendedClient>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientByCode' : ActorMethod<[bigint], [] | [ExtendedClient]>,
  'getClientProgress' : ActorMethod<[bigint], Array<ClientProgress>>,
  'getClientSummaries' : ActorMethod<[], Array<ClientSummary>>,
  'getClientsByFollowUpDay' : ActorMethod<[FollowUpDay], Array<ExtendedClient>>,
  'getExpiringClients' : ActorMethod<[], Array<ExtendedClient>>,
  'getFollowUpHistory' : ActorMethod<[bigint], Array<FollowUpEntry>>,
  'getNonActivatedClientSummaries' : ActorMethod<
    [],
    {
      'fullOnboardedClients' : Array<ClientSummary>,
      'halfOnboardedClients' : Array<ClientSummary>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pauseClient' : ActorMethod<[bigint, bigint, string], undefined>,
  'recordFollowUp' : ActorMethod<
    [bigint, FollowUpDay, boolean, string],
    undefined
  >,
  'resetOnboardingState' : ActorMethod<[bigint], undefined>,
  'resumeClient' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFollowUpDay' : ActorMethod<[bigint, FollowUpDay], undefined>,
  'updateOnboardingState' : ActorMethod<[bigint, OnboardingState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];