/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OnboardingState = IDL.Variant({
  'full' : IDL.Null,
  'half' : IDL.Null,
});
export const Time = IDL.Int;
export const ClientStatus = IDL.Variant({
  'active' : IDL.Null,
  'paused' : IDL.Null,
});
export const Subscription = IDL.Record({
  'endDate' : Time,
  'createdAt' : Time,
  'extraDays' : IDL.Nat,
  'planDurationDays' : IDL.Nat,
  'startDate' : Time,
});
export const PauseEntry = IDL.Record({
  'durationDays' : IDL.Nat,
  'resumed' : IDL.Bool,
  'timestamp' : Time,
  'reason' : IDL.Text,
});
export const FollowUpDay = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const FollowUpEntry = IDL.Record({
  'done' : IDL.Bool,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'followUpDay' : FollowUpDay,
});
export const ClientProgress = IDL.Record({
  'thighInch' : IDL.Float64,
  'chestInch' : IDL.Float64,
  'neckInch' : IDL.Float64,
  'hipsInch' : IDL.Float64,
  'weightKg' : IDL.Float64,
  'timestamp' : Time,
  'waistInch' : IDL.Float64,
});
export const ExtendedClient = IDL.Record({
  'status' : ClientStatus,
  'subscriptions' : IDL.Vec(Subscription),
  'pauseEntries' : IDL.Vec(PauseEntry),
  'activatedAt' : IDL.Opt(Time),
  'code' : IDL.Nat,
  'name' : IDL.Text,
  'pauseTime' : IDL.Opt(Time),
  'totalPausedDuration' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'followUpHistory' : IDL.Vec(FollowUpEntry),
  'progress' : IDL.Vec(ClientProgress),
  'notes' : IDL.Text,
  'followUpDay' : IDL.Opt(FollowUpDay),
  'onboardingState' : OnboardingState,
});
export const SubscriptionSummary = IDL.Record({
  'endDate' : Time,
  'extraDays' : IDL.Nat,
  'planDurationDays' : IDL.Nat,
  'startDate' : Time,
});
export const ClientSummary = IDL.Record({
  'status' : ClientStatus,
  'activatedAt' : IDL.Opt(Time),
  'code' : IDL.Nat,
  'name' : IDL.Text,
  'pauseTime' : IDL.Opt(Time),
  'mobileNumber' : IDL.Text,
  'subscriptionSummary' : IDL.Opt(SubscriptionSummary),
  'followUpDay' : IDL.Opt(FollowUpDay),
  'onboardingState' : OnboardingState,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AppInitData = IDL.Record({
  'userProfile' : IDL.Opt(UserProfile),
  'clientSummaries' : IDL.Vec(ClientSummary),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProgress' : IDL.Func(
      [
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, OnboardingState],
      [IDL.Nat],
      [],
    ),
  'createOrRenewSubscription' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, Time],
      [],
      [],
    ),
  'expireMembershipImmediately' : IDL.Func([IDL.Nat], [], []),
  'filterClientsByOnboardingState' : IDL.Func(
      [OnboardingState],
      [IDL.Vec(ExtendedClient)],
      ['query'],
    ),
  'getActivatedClientSummaries' : IDL.Func(
      [],
      [IDL.Vec(ClientSummary)],
      ['query'],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(ExtendedClient)], ['query']),
  'getAllClientsAndNonActivatedClients' : IDL.Func(
      [],
      [
        IDL.Record({
          'fullOnboardedClients' : IDL.Vec(ExtendedClient),
          'halfOnboardedClients' : IDL.Vec(ExtendedClient),
          'activatedClients' : IDL.Vec(ExtendedClient),
        }),
      ],
      ['query'],
    ),
  'getAppInitData' : IDL.Func([], [AppInitData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientByCode' : IDL.Func([IDL.Nat], [IDL.Opt(ExtendedClient)], ['query']),
  'getClientProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClientProgress)],
      ['query'],
    ),
  'getClientSummaries' : IDL.Func([], [IDL.Vec(ClientSummary)], ['query']),
  'getClientsByFollowUpDay' : IDL.Func(
      [FollowUpDay],
      [IDL.Vec(ExtendedClient)],
      ['query'],
    ),
  'getCurrentSubscription' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SubscriptionSummary)],
      ['query'],
    ),
  'getExpiringClients' : IDL.Func([], [IDL.Vec(ExtendedClient)], ['query']),
  'getFollowUpHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FollowUpEntry)],
      ['query'],
    ),
  'getNonActivatedClientSummaries' : IDL.Func(
      [],
      [
        IDL.Record({
          'fullOnboardedClients' : IDL.Vec(ClientSummary),
          'halfOnboardedClients' : IDL.Vec(ClientSummary),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pauseClient' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'recordFollowUp' : IDL.Func(
      [IDL.Nat, FollowUpDay, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'resetOnboardingState' : IDL.Func([IDL.Nat], [], []),
  'resumeClient' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFollowUpDay' : IDL.Func([IDL.Nat, FollowUpDay], [], []),
  'updateOnboardingState' : IDL.Func([IDL.Nat, OnboardingState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OnboardingState = IDL.Variant({ 'full' : IDL.Null, 'half' : IDL.Null });
  const Time = IDL.Int;
  const ClientStatus = IDL.Variant({
    'active' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'endDate' : Time,
    'createdAt' : Time,
    'extraDays' : IDL.Nat,
    'planDurationDays' : IDL.Nat,
    'startDate' : Time,
  });
  const PauseEntry = IDL.Record({
    'durationDays' : IDL.Nat,
    'resumed' : IDL.Bool,
    'timestamp' : Time,
    'reason' : IDL.Text,
  });
  const FollowUpDay = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const FollowUpEntry = IDL.Record({
    'done' : IDL.Bool,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'followUpDay' : FollowUpDay,
  });
  const ClientProgress = IDL.Record({
    'thighInch' : IDL.Float64,
    'chestInch' : IDL.Float64,
    'neckInch' : IDL.Float64,
    'hipsInch' : IDL.Float64,
    'weightKg' : IDL.Float64,
    'timestamp' : Time,
    'waistInch' : IDL.Float64,
  });
  const ExtendedClient = IDL.Record({
    'status' : ClientStatus,
    'subscriptions' : IDL.Vec(Subscription),
    'pauseEntries' : IDL.Vec(PauseEntry),
    'activatedAt' : IDL.Opt(Time),
    'code' : IDL.Nat,
    'name' : IDL.Text,
    'pauseTime' : IDL.Opt(Time),
    'totalPausedDuration' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'followUpHistory' : IDL.Vec(FollowUpEntry),
    'progress' : IDL.Vec(ClientProgress),
    'notes' : IDL.Text,
    'followUpDay' : IDL.Opt(FollowUpDay),
    'onboardingState' : OnboardingState,
  });
  const SubscriptionSummary = IDL.Record({
    'endDate' : Time,
    'extraDays' : IDL.Nat,
    'planDurationDays' : IDL.Nat,
    'startDate' : Time,
  });
  const ClientSummary = IDL.Record({
    'status' : ClientStatus,
    'activatedAt' : IDL.Opt(Time),
    'code' : IDL.Nat,
    'name' : IDL.Text,
    'pauseTime' : IDL.Opt(Time),
    'mobileNumber' : IDL.Text,
    'subscriptionSummary' : IDL.Opt(SubscriptionSummary),
    'followUpDay' : IDL.Opt(FollowUpDay),
    'onboardingState' : OnboardingState,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AppInitData = IDL.Record({
    'userProfile' : IDL.Opt(UserProfile),
    'clientSummaries' : IDL.Vec(ClientSummary),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProgress' : IDL.Func(
        [
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, OnboardingState],
        [IDL.Nat],
        [],
      ),
    'createOrRenewSubscription' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, Time],
        [],
        [],
      ),
    'expireMembershipImmediately' : IDL.Func([IDL.Nat], [], []),
    'filterClientsByOnboardingState' : IDL.Func(
        [OnboardingState],
        [IDL.Vec(ExtendedClient)],
        ['query'],
      ),
    'getActivatedClientSummaries' : IDL.Func(
        [],
        [IDL.Vec(ClientSummary)],
        ['query'],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(ExtendedClient)], ['query']),
    'getAllClientsAndNonActivatedClients' : IDL.Func(
        [],
        [
          IDL.Record({
            'fullOnboardedClients' : IDL.Vec(ExtendedClient),
            'halfOnboardedClients' : IDL.Vec(ExtendedClient),
            'activatedClients' : IDL.Vec(ExtendedClient),
          }),
        ],
        ['query'],
      ),
    'getAppInitData' : IDL.Func([], [AppInitData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientByCode' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExtendedClient)],
        ['query'],
      ),
    'getClientProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClientProgress)],
        ['query'],
      ),
    'getClientSummaries' : IDL.Func([], [IDL.Vec(ClientSummary)], ['query']),
    'getClientsByFollowUpDay' : IDL.Func(
        [FollowUpDay],
        [IDL.Vec(ExtendedClient)],
        ['query'],
      ),
    'getCurrentSubscription' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SubscriptionSummary)],
        ['query'],
      ),
    'getExpiringClients' : IDL.Func([], [IDL.Vec(ExtendedClient)], ['query']),
    'getFollowUpHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FollowUpEntry)],
        ['query'],
      ),
    'getNonActivatedClientSummaries' : IDL.Func(
        [],
        [
          IDL.Record({
            'fullOnboardedClients' : IDL.Vec(ClientSummary),
            'halfOnboardedClients' : IDL.Vec(ClientSummary),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pauseClient' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'recordFollowUp' : IDL.Func(
        [IDL.Nat, FollowUpDay, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'resetOnboardingState' : IDL.Func([IDL.Nat], [], []),
    'resumeClient' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFollowUpDay' : IDL.Func([IDL.Nat, FollowUpDay], [], []),
    'updateOnboardingState' : IDL.Func([IDL.Nat, OnboardingState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };